services:
  - type: web
    name: portfolio
    env: rust
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/my-portfolio
    envVars:
      - key: RUST_LOG
        value: info